### ISSUE TITLE
useRjEffect should be part of the rj core?

### ISSUE THREAD

**Issue by gffuma** [inmagik/react-rocketjump#11]
Using the new `rj` most of the times i find my self to do the same thing, (this is 99.99% true for GET requests):

```js

const myApi = (a, b, c) => fetch(`/myapi?a=${a}&b=${b}&c=${c}`)

const MyRjState = rj(myApi)

// later in React Component

const MyComponent = ({ a, b, c }) => {
  const [
    { data },
    { run, clean }
  ] = useRj(MyRjState)

  useEffect(() => {
    run(a, b, c)
    return () => clean()
   }, [a, b, c])

  // render
}  

```

So i write a very tiny helper i paste it here because is really tiny:
```js
export function useRjEffect(
  rjObject,
  deps = [],
  cleanOnNewEffect = true,
  selectState,
  mapActions
) {
  const [state, actions] = useRj(rjObject, selectState, mapActions)
  const { run, clean } = actions

  useEffect(() => {
    run(...deps)
    return () => {
      if (cleanOnNewEffect) {
        clean()
      }
    }
  },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [run, clean, cleanOnNewEffect, ...deps]
  )

  return [state, actions]
}
```

So the componente above become:
```js
const MyComponent = ({ a, b, c }) => {
  const [
    { data },
  ] = useRjEffect(MyRjState, [a, b, c])

  // render
}  
```

Much better.

do you think `useRjEffect` should be in the core of `react-rocketjump`?

Thanks for the attention 😄

**Comment by bianchimro** [comment]
Yes @gffuma, i think we should include it.
This is a very common use case and gives a really good reason to use hooks vs the hoc strategy.

Should we consider a `useLayoutEffect` version?

**Comment by osioalberto** [comment]
I think this could be a useful util in many cases, at least in REST based environments: usually, resources have many page they are read in, but few pages able to edit them.

However, there are some points to be discussed
1. It might be possible, in principle, to create an even more aggressive helper, which takes directly `myApi` and not `MyRjState`. Personally, I like the explicit creation of `MyRjState` since it allows for reusability of the state itself, but it might be an idea to consider.
2. About the `mapActions` parameter, it might cause some problems, for instance in the case it renames `run` and `clean` actions to something else. 

    I would see better a solution like
    ```js
    export function useRjEffect(
        rjObject,
        deps = [],
        cleanOnNewEffect = true,
        selectState,
        mapActions
    ) {
        const [state, actions] = useRj(rjObject, selectState)
        const { run, clean } = actions

        useEffect(() => {
            run(...deps)
            return () => {
            if (cleanOnNewEffect) {
                clean()
            }
            }
        },
            // eslint-disable-next-line react-hooks/exhaustive-deps
            [run, clean, cleanOnNewEffect, ...deps]
        )

        return [state, mapActions(actions)] // or something like this
    }
    ```
3. I would rename `deps` to `args`, for clarity of how it is used
4. About the `useLayoutEffect` version, I would stick with `useEffect`. `useLayoutEffect` might introduce blocking updates and UI freezes in some cases, since it is fired synchronously before DOM repaintings. As of React docs, it is recommented to start with `useEffect` and in case of issue switch to `useLayoutEffect` [reference](https://reactjs.org/docs/hooks-reference.html#uselayouteffect)
5. The name `useRjEffect` might be misleading: we always use effects managed by rj, so where is the difference? I would choose a name that highlights the fact that it does not require user actions to run properly, such as `useAutoRj` or `useDataRj`, since it is a simple data loader
